<?php

namespace Becker\WebAppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AnfrageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnfrageRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT b FROM BeckerWebAppBundle:Anfrage b ORDER BY b.name ASC'
            )
            ->getResult();
    } 
}
