<?php

namespace Becker\WebAppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BuehneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuehneRepository extends EntityRepository
{
    public function findAllOrderedByName()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT b FROM BeckerWebAppBundle:Buehne b ORDER BY b.name ASC'
            )
            ->getResult();
    } 
    
}
